
CREATE TABLE `DBuy` ( `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, 
`name` varchar(64) DEFAULT NULL, 
`brand` varchar(64) DEFAULT NULL, 
`prdc` varchar(32) DEFAULT NULL, 
`sex` varchar(6) DEFAULT NULL, 
`materia` varchar(64) DEFAULT NULL, 
`dimension` varchar(64) DEFAULT NULL, 
`third_party_seq` varchar(32) DEFAULT NULL,
`group_name` varchar(32) DEFAULT NULL,
`intra_mirror_id` varchar(16)  DEFAULT NULL,
`size` varchar(64) DEFAULT NULL, 
`store` varchar(64) DEFAULT NULL, 
`price` int(11) DEFAULT 0, 
`t_price` int(11) DEFAULT 0, 
`china_yuan` int(11) DEFAULT 0, 
`description` varchar(256) DEFAULT NULL, 
`p_pic` text, 
`g_pic` text, 
PRIMARY KEY (`id`) ) DEFAULT CHARSET=utf8;


CREATE TABLE `ImGood` ( `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, 
`name` varchar(64) DEFAULT NULL, 
`brand` varchar(64) DEFAULT NULL, 
`prdc` varchar(32) DEFAULT NULL, 
`sex` varchar(6) DEFAULT NULL, 
`materia` varchar(64) DEFAULT NULL, 
`dimension` varchar(64) DEFAULT NULL, 
`group_name` varchar(32) DEFAULT NULL,
`intra_mirror_id` varchar(16)  DEFAULT NULL,
`size` varchar(64) DEFAULT NULL, 
`store` varchar(64) DEFAULT NULL, 
`price` int(11) DEFAULT 0, 
`t_price` int(11) DEFAULT 0, 
`china_yuan` int(11) DEFAULT 0, 
`description` varchar(256) DEFAULT NULL, 
`p_pic` text, 
`g_pic` text, 
PRIMARY KEY (`id`) ) DEFAULT CHARSET=utf8;
