
CREATE TABLE `DBuy` ( `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, 
`name` varchar(64) DEFAULT NULL, 
`brand` varchar(64) DEFAULT NULL, 
`prdc` varchar(32) DEFAULT NULL, 
`sex` varchar(6) DEFAULT NULL, 
`materia` varchar(64) DEFAULT NULL, 
`dimension` varchar(64) DEFAULT NULL, 
`third_party_seq` varchar(32) DEFAULT NULL,
`group_name` varchar(32) DEFAULT NULL,
`intra_mirror_id` varchar(16)  DEFAULT NULL,
`size` varchar(64) DEFAULT NULL, 
`store` varchar(64) DEFAULT NULL, 
`price` int(11) DEFAULT 0, 
`t_price` int(11) DEFAULT 0, 
`china_yuan` int(11) DEFAULT 0, 
`description` varchar(256) DEFAULT NULL, 
`p_pic` text, 
`g_pic` text, 
PRIMARY KEY (`id`), INDEX(`brand`), INDEX(`group_name`)) DEFAULT CHARSET=utf8;


CREATE TABLE `ImGood4` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) DEFAULT NULL,
  `brand` varchar(64) DEFAULT NULL,
  `prdc` varchar(32) DEFAULT NULL,
  `country` varchar(64) DEFAULT NULL,
  `sex` varchar(6) DEFAULT NULL,
  `materia` varchar(1000) DEFAULT NULL,
  `materia_uniq` varchar(1000) DEFAULT NULL,
  `color` varchar(64) DEFAULT NULL,
  `color_uniq` varchar(64) DEFAULT NULL,
  `categary_1` varchar(32) DEFAULT NULL,
  `categary_2` varchar(32) DEFAULT NULL,
  `dimension` varchar(64) DEFAULT NULL,
  `group_name` varchar(32) DEFAULT NULL,
  `intra_mirror_id` varchar(16) DEFAULT NULL,
  `size` varchar(64) DEFAULT NULL,
  `size_uniq` varchar(64) DEFAULT NULL,
  `store` varchar(64) DEFAULT NULL,
  `price` int(11) DEFAULT '0',
  `t_price` int(11) DEFAULT '0',
  `china_yuan` int(11) DEFAULT '0',
  `description` varchar(256) DEFAULT NULL,
  `pic_dir`varchar(256) DEFAULT NULL,
  `p_pic` text,
  `g_pic` text,
  `similar_goods` text,
  `same_goods` text,
  PRIMARY KEY (`id`),
  KEY `brand` (`brand`),
  KEY `group_name` (`group_name`),
  KEY `idx_intra_mirror_id` (`intra_mirror_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8


